config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root to: 'welcome#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :reservations, only: [:index, :new, :create, :show]
  
  resources :rooms
  #resources :rooms do
    #resources :reservations, only: [:new, :create, :index]
  #end

  resources :facilities

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  REGIONS = ['東京', '大阪', '京都', '札幌']

  # その他のバリデーションやアソシエーション
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }, on: :create
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  def index
    @facilities = Facility.all
  end

  def show
    @facility = Facility.find(params[:id])
  end

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facility_params)
    if @facility.save
      redirect_to @facility
    else
      render 'new'
    end
  end

  private

  def facility_params
    params.require(:facility).permit(:name, :address, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
    @reservations = current_user.reservations
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @room = Room.find(params[room_id])
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @room = Room.find(params[:room_id])
    @reservation = @room.reservations.new(reservation_params)
    @reservation.user = current_user

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to room_path(@room), notice: '予約が完了しました' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:check_in, :check_out, :guests, :user_id, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]
  before_action :authenticate_user!  # ユーザーがログインしているかを確認

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
    if params[:query].present?
      @rooms = @rooms.where('name LIKE ? OR address LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    end
  
    # 地域での検索条件を追加
    if params[:region].present?
      @rooms = @rooms.where(region: params[:region])
    end
  end
end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password_digest, :profile)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
      end
    
      def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    
      def logged_in?
        !current_user.nil?
      end
    
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.date_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.date_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :guests %>
    <%= form.number_field :guests %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>予約済み一覧</h1>

<table>
  <thead>
    <tr>
      <th>Check in</th>
      <th>Check out</th>
      <th>Guests</th>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.check_in %></td>
        <td><%= reservation.check_out %></td>
        <td><%= reservation.guests %></td>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.room_id %></td>
        <td><%= link_to '詳細', reservation %></td>
        <td><%= link_to '編集', edit_reservation_path(reservation) %></td>
        <td><%= link_to '削除', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @reservation.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @reservation.check_out %>
</p>

<p>
  <strong>Guests:</strong>
  <%= @reservation.guests %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
   <%= form.label :region, '地域' %>
    <%= form.select :region, Room::REGIONS, prompt: '地域を選択してください' %>
</div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>施設一覧</h1>
<%= link_to '新しい施設を追加', new_room_path %>

<%# 施設検索機能%>
<%= form_with url: rooms_path, method: :get, local: true do |form| %>
  <div>
    <%= form.label :query, "施設検索" %>
    <%= form.text_field :query %>
    <%= form.submit "検索" %>
  </div>
<% end %>


<table>
  <thead>
    <tr>
      <th>名称</th>
      <th>Description</th>
      <th>価格</th>
      <th>住所</th>
      <th>地域</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.name, room_path(room) %></td>
        <p>地域: <%= room.region %></p>
        <p>住所: <%= room.address %></p>
        <p>価格: <%= number_to_currency(room.price) %></p>
        <td><%= room.description %></td>
        <td><%= number_to_currency(room.price) %></td>
        <td><%= room.address %></td>
        <td><%= image_tag room.image if room.image.present? %></td>
        <td><%= room.user_id %></td>
        <td><%= link_to '一覧', room %></td>
        <td><%= link_to '詳細', edit_room_path(room) %></td>
        <td><%= link_to '削除', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rooms/my_rooms.html.erb
<h1>登録済み宿泊所</h1>
<ul>
  <% @rooms.each do |room| %>
    <li><%= room.name %> - <%= room.address %></li>
  <% end %>
</ul>

app/views/rooms/new.html.erb
<h1>新しい部屋を作成</h1>

<%= form_with model: @room, local: true do |f| %>
  <div>
    <%= f.label :name, '施設名' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description, '説明' %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :price, '料金' %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :address, '住所' %>
    <%= f.text_field :address %>
  </div>
  <%= f.submit '登録する' %>
<% end %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name(施設名称):</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price(料金):</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Address(住所):</strong>
  <%= @room.address %>
</p>

<p>
  <strong>Image(詳細画像):</strong>
  <%= @room.image %>
</p>

<p>
  <strong>User(ユーザー):</strong>
  <%= @room.user_id %>
</p>

<%= form_with model: [@room, @reservation], local: true do |f| %>
  <%= f.label :start_date, 'チェックイン日' %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date, 'チェックアウト日' %>
  <%= f.date_field :end_date %>
  <%= f.submit '予約する' %>
<% end %>

<%= link_to '更新', edit_room_path(@room) %> |
<%= link_to '施設一覧に戻る', rooms_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :profile %>
    <%= form.text_field :profile %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.profile %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @user.profile %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <h1>Potepan Share</h1>
    <nav>
      <ul>
        <% if user_signed_in? %>
          <li class="nav-item NavItem">Logged in as <%= current_user.email %></li>
          <li class="nav-item NavItem"><%= link_to 'Settings', edit_user_registration_path %></li>
          <li class="nav-item NavItem"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="nav-item NavItem"><%= link_to 'ログイン', new_user_session_path %></li>
          <li class="nav-item NavItem"><%= link_to '新規登録', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>

  <div class="FirstView">
    <section class="container">
      <h2 class="FirstView__title">
        potepanshareで<br>
        まだ体験したことのない旅をしよう
      </h2>
      <div class="FirstViewSearch">
        <%# 検索機能 %>
        <%= form_with url: rooms_path, method: :get, local: true, data: { turbo_frame: "_self" } do |form| %>
          <div>
            <%= form.label :query, "施設検索" %>
            <%= form.text_field :query %>
            <%= form.submit "検索" %>
          </div>
        <% end %>
      </div>
    </section>
  </div>

  <footer>Potepan Share</footer>
</body>